# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Dare.create(text: "Take a shot", :points => 1, :shots=>0)
Dare.create(text: "Take two shots", :points => 2, :shots=>1)
Dare.create(text: "Pick someone to take two shots", :points => 1, :shots=>1)
Dare.create(text: "Do whatever [RandomPlayer] tells you to do", :points => 1, :shots=>1)
Dare.create(text: "Dare [RandomPlayer] to do whatever you want", :points => 1, :shots=>1)
Dare.create(text: "You must do your next dare", :points => 1, :shots=>3)
Dare.create(text: "lick the floor", :points => 2, :shots=>1)
Dare.create(text: "Choose someone to give you a wedgie", :points => 1, :shots=>2)
Dare.create(text: "Stick your finger up your nose, then lick your finger", :points => 1, :shots=>1)
Dare.create(text: "Lick [RandomPlayer]'s elbow", :points => 1, :shots=>1)
Dare.create(text: "Hop on one foot to the front door and back without loosing your balance", :points => 1, :shots=>1)
Dare.create(text: "Do a handstand if the group is not satisfied take a shot", :points => 1, :shots=>1)
Dare.create(text: "Give [RandomPlayer] a rough piggy back ride around the room", :points => 1, :shots=>1)
Dare.create(text: "You have to do [RandomPlayer]'s next dare with them", :points => 1, :shots=>1)
Dare.create(text: "Take a shot with [RandomPlayer]", :points => 1, :shots=>0)
Dare.create(text: "Choose someone to take a shot and loose a point (if you pass you still lose a point)", :points => -1, :shots=>1)
Dare.create(text: "Free turn", :points => 0, :shots=>0)
Dare.create(text: "Take two shots", :points => 1, :shots=>1)
Dare.create(text: "Do whatever [RandomPlayer] tells you to do", :points => 1, :shots=>1)
Dare.create(text: "Dare [RandomPlayer] to do whatever you want", :points => 1, :shots=>1)
Dare.create(text: "lick [RandomPlayer]'s toes:", :points => 1, :shots=>1)
Dare.create(text: "Choose someone to give you a wedgie", :points => 1, :shots=>1)
Dare.create(text: "Stick your finger up your nose and then lick your finger", :points => 2, :shots=>2)
Dare.create(text: "Lick [RandomPlayer]'s elbow", :points => 2, :shots=>1)
Dare.create(text: "Wear socks on your hands for the rest of the game", :points => 1, :shots=>3)
Dare.create(text: "Hop on one foot to the front door and back if you lose your balance take a shot", :points => 1, :shots=>1)
Dare.create(text: "Do a handstand if the group is not satisfied take a shot", :points => 2, :shots=>1)
Dare.create(text: "Give [RandomPlayer] a rough piggy back ride around the room", :points => 1, :shots=>1)
Dare.create(text: "You have to do [RandomPlayer]'s next dare with them", :points => 1, :shots=>1)
Dare.create(text: "Take a shot with [RandomPlayer]", :points => 1, :shots=>0)
Dare.create(text: "Choose a word going in a circle everyone must rhyme with that word with no repeats. if someone messes up they take a shot", :points => 1, :shots=>0)
Dare.create(text: "You are the master! If you hold your finger to your nose at any point the last person to also do so has to take a shot", :points => 1, :shots=>0)
Dare.create(text: "You can not speak until you successfully complete a dare", :points => 1, :shots=>1)
Dare.create(text: "Tie your hands behind your back for YOUR next two turns", :points => 1, :shots=>3)
Dare.create(text: "Say a word to start a story and continue it in a circle if a person hesitates they take a shot", :points => 1, :shots=>0)
Dare.create(text: "Make a fart nose with [RandomPlayer]'s belly button", :points => 2, :shots=>2)
Dare.create(text: "You get to arrange everyone anyway you choose and take a picture", :points => 1, :shots=>1)
Dare.create(text: "Let  [RandomPlayer] give you a wet willy", :points => 1, :shots=>2)
Dare.create(text: "Make out the closet door knob for 7 seconds", :points => 2, :shots=>1)
Dare.create(text: "Take a shot of something not meant to be drank alone", :points => 2, :shots=>2)
Dare.create(text: "everyone take a shot", :points => 1, :shots=>0)
Dare.create(text: "remove the socks of [RandomPlayer] using your teeth", :points => 2, :shots=>1)
Dare.create(text: "talk continuously for the next 5 mins", :points => 1, :shots=>1)
Dare.create(text: "smell every players feet ", :points => 2, :shots=>1)
Dare.create(text: "apply petroleum jelly or lotion to your face but do not rub it in", :points => 1, :shots=>2)
Dare.create(text: "speak like Scooby-Doo  for the rest of the game", :points => 2, :shots=>1)
Dare.create(text: "do a handstand on the the wall for the next two rounds", :points => 3, :shots=>1)
Dare.create(text: "talk without closing your mouth for the next 5 turns", :points => 2, :shots=>1)
Dare.create(text: "drop ice down your pants", :points => 3, :shots=>2)
Dare.create(text: "send [RandomPlayer] x amount of dollars (x is the number of penalty shots you have taken). Or take 3 shots", :points => 3, :shots=>2) 
Dare.create(text: "swap your pants with your shirt", :points => 2, :shots=> 2)
Dare.create(text: "free point", :points => 1, :shots=> 0)
Dare.create(text: "lose a point (if you pass you still lose a point)", :points => -1, :shots=>1)
Dare.create(text: "Exchange shirts with the player after you", :points =>2, :shots=>1 )
Dare.create(text: "Suck your big toe", :points =>2, :shots=> 2)
Dare.create(text: "Allow the person to your right to tickle you for x seconds (x is the number of penalty shots you have)", :points => 2, :shots => 3)
Dare.create(text: "Do 15 pushups", :points => 1, :shots=> 1)
Dare.create(text: "Sniff the armpit of everyone in the room and rank them best to worst", :points =>1, :shots=>2 )
Dare.create(text: "Stick your bare foot in the toilet", :points =>2, :shots=> 2)
Dare.create(text: "Lick a bar of soap", :points =>1, :shots=> 2)
Dare.create(text: "Be blindfolded for the rest of the game", :points =>2, :shots=>1 )

